### ISSUE TITLE
How to connect to wifi

### ISSUE THREAD

**Issue by jerryzhao173985** [sunfounder/picar-x#10]
Hi, how to connect this raspberry pi using ezblock image to wifi and set wifi country. The camera module is not working and I cannot figure out ways to connect Picar-X to wifi, only bluetooth connection. Any help is appreciated.

**Comment by gotthub** [comment]
Initially you should set up your Wifi with wpa_supplicant.conf in /boot directory on the SD card, usual way for headless Pi operation. 
Then I found that in all Python examples that use the camera, the Wifi settings are being reset to some Sunfounder defaults. 
You should remove or reconfigure these lines in the programs. It is a very annoying issue.

**Comment by gotthub** [comment]
See here also: https://github.com/ezblockcode/ezb-pi/issues/2

**Comment by jcboyer** [comment]
Using the newest Raspberry  Image Loader, one can set the Wi-Fi before the image is created.
If stuck, ssh with sudo raspi-config gives access to the Wi-Fi  set up.
I have no problem with Wi-Fi. But I cannot connect using Bluetooth,  I read something about a special dongle?
