### ISSUE TITLE
What is the picar-x?

### ISSUE THREAD

**Issue by yuvilio** [sunfounder/picar-x#3]
Hi, very silly question. Is this an upcoming new Raspberri Pi based car model? (like Picar-V or Picar-S, ...) Or is this more just software that works with the other ones?

Thanks!

**Comment by amity137** [comment]
This has camera, speaker, ultrasonic, grayscale. This should work with different Pi models. You can refer to the documentation https://docs.sunfounder.com/_/downloads/picar-x/en/latest/pdf/
