### ISSUE TITLE
Ezblock versions - Desktop (not on windows) - Phone? Web ?

### ISSUE THREAD

**Issue by jcboyer** [sunfounder/picar-x#52]
Can someone document which version works on which system and the most current one. 

I understand this GIT is for Python, but is not Easyblock driven from Python? In other words, can we code in Python and see it in the UI?

If I look confused,. it is because I suspect I am trying to run the Picar-X using wrong UI version.

Picar reminds of Star Trek's Cpt Picard! I wonder if the pun was intended.

**Comment by reiswizard** [comment]
You can use Exblock in your browser:
http://ezblock.cc/ezblock_studio/beta/index.html?lang=en
