### ISSUE TITLE
Git is a Code repository first. Can it be used for Hardware issues or questions?

### ISSUE THREAD

**Issue by jcboyer** [sunfounder/picar-x#55]
There is a tight link between 'robotic' software and hardware. In some cases, the hardware constraints will take over the code constraints.

For example, the Picar-x may behave differently based on which PI it is based on. Its HAT may not work with Version xx of the Raspberry OS - or other OSes.

I see these issues part of updated documentation,, of course, but also being reported in Github as issues. (Filling the void of the missing Forum.)

Any thoughts?

**Comment by amity137** [comment]
Yeah given there are no forums or other means of communication, this place seems like the best to track any kind of issues? But there is very activity here than I'd have liked.
