### ISSUE TITLE
Where is the install.py file?

### ISSUE THREAD

**Issue by reiswizard** [sunfounder/picar-x#56]
I am following the instruction from the documentation.
I am at this point:
https://docs.sunfounder.com/projects/picar-x/en/latest/download_and_run_code.html

is done:
git clone -b v2.0 https://github.com/sunfounder/picar-x.git

but i can't do: sudo python3 install.py

because there is no such file.

Can someone help me please.

**Comment by amity137** [comment]
The branch name is V2.0 and it indeed has the install.py. I just assembled my picar-x yesterday. Is your git clone successful?

**Comment by reiswizard** [comment]
> The branch name is V2.0 and it indeed has the install.py. I just assembled my picar-x yesterday. Is your git clone successful?

Ah thx you very much...that was my mistake, i was using the git clone from the instruction site. I test it tomorrow again.

**Comment by reiswizard** [comment]
Okay after Git Clone is successful and install.py is finished

I can't execute move.py

It's this error: OSError: [Errno 121] Remote I/O error

I already trying with activating I2C and so on...no help, can someone tell me what wrong...i mean i follow the tutorial step for step this time, and it's still doesn't work
